WebUI/Controllers/WriterPanelController/WriterHeadingController.cs
using Business.Concrete;
using DataAccess.EntityFramework;
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace WebUI.Controllers.WriterPanelController
{
    public class WriterHeadingController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());
        int id;
        public ActionResult MyHeading(string p)
        {
            p = (string)Session["WriterMail"];
           var writerinfo = wm.GetWriters().Where(x => x.WriterMail == p).Select(y => y.WriterId).FirstOrDefault();
            var results = hm.GetHeadingsByWriter(writerinfo);
            return View(results);
        }
        [HttpGet]
        public ActionResult NewHeading()
        {
          
            
            List<SelectListItem> selects = (from x in cm.GetCategories()
                                            select new SelectListItem
                                            {

                                                Text = x.CategoryName,
                                                Value = x.CategoryId.ToString()

                                            }).ToList();
            ViewBag.vlc = selects;
            return View();
        }
        [HttpPost]
        public ActionResult NewHeading(Heading heading)
        {
            string m = (string)Session["WriterMail"];
            var writerinfo = wm.GetWriters().Where(x => x.WriterMail == m).Select(y => y.WriterId).FirstOrDefault();
            heading.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            heading.WriterId = writerinfo;
            heading.HeadingStatus = true;
            hm.Add(heading);
            return RedirectToAction("MyHeading");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {

            List<SelectListItem> selects = (from x in cm.GetCategories()
                                            select new SelectListItem
                                            {
                                                Text = x.CategoryName,
                                                Value = x.CategoryId.ToString()
                                            }).ToList();



            ViewBag.vlc = selects;
            var values = hm.GetById(id);
            return View(values);
        }

        public ActionResult EditHeading(Heading heading)
        {
            hm.Update(heading);
            return RedirectToAction("MyHeading");
        }

        public ActionResult DeleteHeading(int id)
        {
            var results = hm.GetById(id);
            results.HeadingStatus = false;
            hm.Delete(results);
            return RedirectToAction("MyHeading");
        }

        public ActionResult AllHeading(int page=1)
        {
            var allheadings = hm.GetHeadings().ToPagedList(page,4);
            return View(allheadings);
        }

    }
}

WebUI/Views/WriterHeading/AllHeading.cshtml
@using Entities.Concrete
@model PagedList.IPagedList<Heading>
@using PagedList.Mvc
@using PagedList

@{
    ViewBag.Title = "AllHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" />
@{ string color = "";}
@{ string durum = "";}
<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Theatre")
                            {
                                color = "badge badge-warning";
                            }
                            if (item.Category.CategoryName == "Education")
                            {
                                color = "badge badge-success";
                            }
                            if (item.Category.CategoryName == "Yazılım")
                            {
                                color = "badge badge-info";
                            }
                            if (item.Category.CategoryName == "Seyahat")
                            {
                                color = "badge badge-secondary";
                            }
                            if (item.Category.CategoryName == "Book")
                            {
                                color = "badge badge-light";
                            }
                            <tr>
                                <td>
                                    @item.HeadingId
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Default/DefaultHeadings/@item.HeadingId">
                                        <i class="fas fa-folder">
                                        </i>
                                        İçerikler
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/WriterContent/AddContent/@item.HeadingId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Bu Başlığa Yaz
                                    </a>
                                   
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>
@Html.PagedListPager((IPagedList)Model,page=>Url.Action("AllHeading", new { page }))

WebUI/Views/WriterHeading/EditHeading.cshtml
@model Entities.Concrete.Heading 
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@using (Html.BeginForm("EditHeading", "WriterHeading", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.HeadingId)
    @Html.HiddenFor(x => x.HeadingDate)
    @Html.HiddenFor(x => x.WriterId)
    @Html.Label("Name")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Adı")
    @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Guncelle</button>
</div>
}

WebUI/Views/WriterHeading/MyHeading.cshtml
@using Entities.Concrete
@model List<Heading>

@{
    ViewBag.Title = "MyHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}


@{ string color = "";}
@{ string durum = "";}
<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Theatre")
                            {
                                color = "badge badge-warning";
                            }
                            if (item.Category.CategoryName == "Education")
                            {
                                color = "badge badge-success";
                            }
                            if (item.Category.CategoryName == "Yazılım")
                            {
                                color = "badge badge-info";
                            }
                            if (item.Category.CategoryName == "Seyahat")
                            {
                                color = "badge badge-secondary";
                            }
                            if (item.Category.CategoryName == "Book")
                            {
                                color = "badge badge-light";
                            }
                            <tr>
                                <td>
                                    @item.HeadingId
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingId">
                                        <i class="fas fa-folder">
                                        </i>
                                        İçerikler
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/WriterHeading/EditHeading/@item.HeadingId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Edit
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/WriterHeading/DeleteHeading/@item.HeadingId">
                                        <i class="fas fa-trash">
                                        </i>
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>
<a href="/WriterHeading/NewHeading" class="btn btn-success">Yeni Başlık Ekle</a>

WebUI/Views/WriterHeading/NewHeading.cshtml
@model Entities.Concrete.Heading
@{
    ViewBag.Title = "NewHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<br />
@using (Html.BeginForm("NewHeading", "WriterHeading", FormMethod.Post))
{
    <div class="form-group">

        @Html.Label("Başlık")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        <div style="color:red">
            @Html.ValidationMessageFor(x => x.HeadingName)
        </div>
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc,
          new { @class = "form-control" })

        <br />
        <button class="btn btn-info">Başlığı Oluştur</button>
    </div>

}