WebUI/Controllers/WriterPanelController/WriterContentController.cs
using Business.Concrete;
using DataAccess.EntityFramework;
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers.WriterPanelController
{
    public class WriterContentController : Controller
    {
        ContentManager cm = new ContentManager(new EfContentDal());
        WriterManager wm = new WriterManager(new EfWriterDal());
        // GET: WriterContent
        public ActionResult MyContent(string p)
        {
            p = (string)Session["WriterMail"];
            var writerinfo = wm.GetWriters().Where(x => x.WriterMail == p).Select(y=>y.WriterId).FirstOrDefault();
            var values = cm.GetContentsByWriter(writerinfo);
            return View(values);
        }
        [HttpGet]
        public ActionResult AddContent(int id)
        {
            ViewBag.d = id;
            return View();
        }
        [HttpPost]
        public ActionResult AddContent(Content content)
        {
            content.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            string mail = (string)Session["WriterMail"];
            var writerinfo = wm.GetWriters().Where(x => x.WriterMail == mail).Select(y => y.WriterId).FirstOrDefault();
            content.WriterId = writerinfo;
            content.ContentStatus = true;
            cm.Add(content);
            return RedirectToAction("MyContent");
        }

        public ActionResult ToDoList()
        {
            return View();
        }

    }
}

WebUI/Views/WriterContent/AddContent.cshtml
@model Entities.Concrete.Content
@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<h1>İçerik Girişi</h1>
<br />
@using (Html.BeginForm("AddContent", "WriterContent", FormMethod.Post))
{
<div class="form-group">
    <input type="hidden" name="HeadingID" value="@ViewBag.d" />
    @Html.Label("İçerik Yazınız ...")
    @Html.TextAreaFor(x => x.ContentValue,10,30, new { @class = "form-control" })
    <div style="color:red">
        @Html.ValidationMessageFor(x => x.ContentValue)
    </div>
    <br />
  
    <button class="btn btn-info">Kaydet</button>
</div>

}

WebUI/Views/WriterContent/MyContent.cshtml
@using Entities.Concrete
@model List<Content>
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            @foreach (var item in Model)
                            {


                                <!-- timeline time label -->
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MM-yyyy"))</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a> </h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            }
                        </div>
                    </div>
                    <!-- /.col -->
                </div>

            </div>

            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

WebUI/Views/WriterContent/ToDoList.cshtml
@{
    ViewBag.Title = "ToDoList";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<p>#1 Profilim sayfası yok</p>
<p>#2 Tüm Başlıklarda Paging</p>
<p>#3 Mesajlarda Session</p>
<p>#4 Oturum yönetimin mimariye taşınması</p>
<p>#5 Token Kullanımı</p>